CREATE TABLE [dbo].[Comments]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Message] NVARCHAR(256) NOT NULL, 
    [Date] DATETIME NOT NULL DEFAULT GETDATE(), 
    [Likes] BIGINT NOT NULL DEFAULT 0, 
    [Dislikes] BIGINT NOT NULL DEFAULT 0, 
    [TripId] BIGINT NOT NULL, 
    [UserId] BIGINT NOT NULL, 
    [AnswerTo] BIGINT NULL,
	CONSTRAINT FK_Comments_Trips FOREIGN KEY(TripId) REFERENCES Trips(Id),
	CONSTRAINT FK_Comments_Users FOREIGN KEY(UserId) REFERENCES Users(Id)
)
